services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: backend_app
    restart: always
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: "postgresql://postgres:123456@db:5432/postgres"
      CHOKIDAR_USEPOLLING: "true"
      NODE_ENV: "development"
    volumes:
      - ./:/usr/src/app
      - node_modules:/usr/src/app/node_modules
    command: npm run dev
    depends_on:
      - db
    networks:
      - app-network

  db:
    image: postgres:latest
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

volumes:
  postgres_data:
  node_modules:

networks:
  app-network: